apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbg-api-app-paul
  labels:
    app: lbg-api-app-paul
spec:
  replicas: 5
  selector:
    matchLabels:
      app: lbg-api-app-paul
  template:
    metadata:
      labels:
        app: lbg-api-app-paul
    spec:
      containers:
      - name: lbg-api-app
        image: {{IMAGE_NAME}}
        ports:
        - containerPort: 8080
